server:
  port: 8088

spring:
  mvc:
    path match:
      matching-strategy: ant-path-matcher
  main:
    allow-circular-references: true

#springdoc:
#  swagger-ui:
#    path: /swagger-ui.html

#management:
#  server:
#    port: 9000
#  endpoint:
#    shutdown:
#      enabled: true


#spring:
#  security:
#    user:
#      name: admin
#      password: admin
